name: Alibaba Scraper Automation

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allows manual execution

jobs:
  scrape_and_etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ Updated to v4

      - name: Set up Python
        uses: actions/setup-python@v4  # ✅ Updated to v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install selenium undetected-chromedriver pandas openpyxl webdriver-manager regex

      - name: Run Scraper
        run: python alibaba_spider.py

      - name: Run ETL Process
        run: python ETL.py

      - name: Upload raw scraped data
        uses: actions/upload-artifact@v4  # ✅ Ensure v4 is used
        with:
          name: product_json
          path: product.json

      - name: Upload cleaned Excel file
        uses: actions/upload-artifact@v4  # ✅ Ensure v4 is used
        with:
          name: cleaned_product_xlsx
          path: cleaned_product.xlsx
